p = input("Please enter principal   ")
r = input("Please enter rate of interest   ")
t = input("Please enter time in number of years   ")
print(type(p))
p = int(p)
r = int(r)
t = int(t)
print(type(p))
si = p*r*t/100
print(si)
